### ISSUE TITLE
Add new API endpoint for FxA concerts

### ISSUE THREAD

**Issue by pmac** [mozmeao/basket#114]
These data will go directly into an SFMC data extension:

```yaml
name: FxAccounts_Concert_RSVP
fields:
  - Email: EmailAddress
  - Firefox: Text (Y or N)
  - Campaign_ID: Text 100
  - RSVP_Time: DateTime
```
